name: rxrisk
dependencies:
    - python=2.7.12
    - nose=1.3.7
    - pandas=0.19.2
    - xlrd=1.0.0
    - pip:
        - pyparsing==2.2.0
        - toolz==0.8.2
        - git+https://github.com/jcrudy/modulecache.git@f8ca2812cadcf195b79b14ac23b3766876a1912e
        - git+https://github.com/jcrudy/clinvoc.git@9176d82d9ff1f5687e348c9d2853e696be7a2d30
